name = "workers-block-ngword-in-post-body"
compatibility_date = "2023-12-01"
main = "./src/index.js"

# [vars]
# MY_VARIABLE = "production_value"

[[kv_namespaces]]
binding = "KV"
id = "23631416a9a54887a78c542277e7ddac"
